In [1]:
# 1. Install required packages (only needed once, re-run if venv is fresh)
#    Pre-built wheels only - works with the regular CPython 3.13 inside ./myenv
%pip install pandas pyarrow nltk regex tqdm

Requirement already satisfied: pandas in c:\Users\91942\OneDrive\Desktop\NLP\myenv\Lib\site-packages (3.0.5)
Requirement already satisfied: pyarrow in c:\Users\91942\OneDrive\Desktop\NLP\myenv\Lib\site-packages (25.0.0)
Requirement already satisfied: nltk in c:\Users\91942\OneDrive\Desktop\NLP\myenv\Lib\site-packages (3.10.1)
Requirement already satisfied: regex in c:\Users\91942\OneDrive\Desktop\NLP\myenv\Lib\site-packages (2026.7.19)
Requirement already satisfied: tqdm in c:\Users\91942\OneDrive\Desktop\NLP\myenv\Lib\site-packages (4.70.0)
Requirement already satisfied: numpy>=1.26.0 in c:\Users\91942\OneDrive\Desktop\NLP\myenv\Lib\site-packages (from pandas) (2.5.1)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\Users\91942\OneDrive\Desktop\NLP\myenv\Lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\Users\91942\OneDrive\Desktop\NLP\myenv\Lib\site-packages (from pandas) (2026.3)
Requirement already satisfied: defusedxml in c:\Users\91942\OneDrive\Desktop\NLP\myenv\Lib\site-packages (from nltk) (0.7.1)
Requirement already satisfied: click in c:\Users\91942\OneDrive\Desktop\NLP\myenv\Lib\site-packages (from nltk) (8.4.2)
Requirement already satisfied: joblib in c:\Users\91942\OneDrive\Desktop\NLP\myenv\Lib\site-packages (from nltk) (1.5.3)
Requirement already satisfied: colorama in c:\Users\91942\OneDrive\Desktop\NLP\myenv\Lib\site-packages (from tqdm) (0.4.6)
Requirement already satisfied: six>=1.5 in c:\Users\91942\OneDrive\Desktop\NLP\myenv\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [2]:
# 2. Load the Gujarati corpus that was converted to Parquet in the previous step
#    The full file is 21.8M rows / 5.5 GB, so we use pyarrow's streaming reader
#    instead of loading everything into memory at once.
import os

input_file  = r"E:\STUDY\NLP\Language\gu.txt"
output_file = r"C:\Users\91942\OneDrive\Desktop\NLP\Lab 1\gujarati.parquet"

### Raw data in txt formate

In [3]:
# 3. Inspect the first 30 lines of the raw text file
with open(input_file, "r", encoding="utf-8") as f:
    for i in range(30):
        line = f.readline()
        print(line.strip())

આ વીડિયો જુઓ: ઊંઝા માર્કેટયાર્ડ આજથી 25 જુલાઈ સુધી બંધ

મિથેનોલ આવ્યો ક્યાંથી?

આખરે ત્રણ રાજ્યોમાં મળેલ હાર પર કોંગ્રેસ અધ્યક્ષ રાહુલ ગાંધી દ્વારા પ્રથમ પ્રતિક્રિયા આપવામાં આવી છે. તેમણે કહ્યું કે, ત્રિપુરા, નાગાલેન્ડ અને મેઘાલયમાં લોકોના જનાદેશનો સ્વાગત કરીએ છે અને આ ક્ષેત્રના લોકોનો વિશ્વાસ ફરીથી જીતીવા માટે પ્રતિબદ્ધ છીએ.

આ આંકડો માટે, અને વજન ઘટાડવા માટે પ્રકાશનનો દિવસ વિતાવવો ઉપયોગી છે, ઉદાહરણ તરીકે, અઠવાડિયામાં એક વખત. તમારા માટે એક વિકલ્પ પસંદ કરો જે અગવડતાને કારણે નહીં કરે. સૌથી વધુ લોકપ્રિય કીફિર પર અનલોડ છે.

આ ઠેકાઓ પરથી લીમડી તેમજ ઝાલોદના બૂટલેગરો વિદેશી દારૃનો મોટાપાયે જથ્થો ખરીદી મહિસાગર, હાલોલ, ગોધરા, આણંદ, નડિયાદ અને વડોદરા શહેર-જિલ્લામાં ઠાલવે છે. આબુથી આવતો દારૃનો જથ્થો સાંચોર તેમજ પાલનપુર થઈ મહેસાણામાં રીટા અને વિરસિંહને ત્યાં ઉતારવામાં આવે છે, જ્યાંથી અમદાવાદ તેમજ ઉત્તર ગુજરાતમાં દારૃ સપ્લાઈ થાય છે. રાજસ્થાનના બિચ્છુવાડાથી શામળાજી બોર્ડર થઈ હિંમતનગર, ગાંધીનગર અને અમદાવાદમાં બૂટલેગર સુનિલ, વિનોદ, દિલીપ અને રબારી દ્વારા મોટાપાયે દારૃનો જથ્થો ઠલવાય છે.

કેન્દ્રીય મંત્રી જ્યોતિરાદિત્ય સિંધિયાની જન આશિર્વાદ યાત્રા દરમિયાન ઈન્દોરના એક પોલીસ સ્ટેશનમાં પ્રાણી ક્રૂરતાનો કેસ નોંધવામાં આવ્યો છે. ભાજપના કાર્યકરોએ જન આશીર્વાદ યાત્રા દરમિયાન...

ઉત્તર પ્રદેશમાં લગભગ 359 બાળ કેદીઓને મુક્ત કરવામાં આવશે. હાઈકોર્ટના નિર્દેશોના પગલે આ કેદીઓને બાળગૃહમાંથી મુકત કરવામાં આવશે. આ કેદીઓને ત્રણ વર્ષ સુધીની સજા કરવામાં આવી છે. રાજ્યના બાળગૃહોમાં લગભગ 30,000 બાળકો બંધ છે. કોર્ટે આ નિર્ણય કોરોના વાયરસના ભયને ધ્યાનમાં રાખીને લીધો છે.

યાત્રા માટે સમય શુભ ના હોવાથી ટાળી દેવી યોગ્ય રહેશે. આ અઠવાડિયે ખર્ચો વધારે થશે. અઠવાડિયાના અંતે કોઈ વાતને લઈને ચિંતા થઈ શકે છે.કર્ક: મહિલા વર્ગના સપોર્ટથી સ્થિતિ સુખદ રહેશે. કેટલાક જાતકો માટે વિવાહનો શુભ યોગ બની રહ્યો છે.

કારણ કે પેટના પ્રદેશમાં વજન આગળ યોનિમાર્ગ ખેંચે છે, સગર્ભા સ્ત્રીઓ અને ખૂબ જ મેદસ્વી લોકો પેટની વિસ્તારમાં તેમના વજન લઇ શકે છે ઘણા કરતાં સ્વવેન માટે ઊંચા જોખમ પર હોઈ શકે છે. "વલણ" ધરાવતા તરુણો એક સ્વવેના મુદ્રામાં તે વલણ વ્યક્ત કરી શકે છે.

ખુબજ મુશ્કેલ હોતુ હતું જ્યારે આપ તે વાતો ફરી વખત સાંભળો છો જે ક્યારેક આપનાં પેરેન્ટ્સે આપને કહી હોય છે. પણ હું ઇચ્છતી હતી કે સીરિઝમાં સત્ય દર્શાવવામાં આવે.

48. જેમના કાન સરળતાથી જોઈ શકાય છે, તેવાં પ્રાણીઓનાં નામ જણાવો. (નમૂનારૂપ ઉત્તર)

આમ, મિલનભાઇ હરીશભાઇ માવાણીએ ચાર્મી ઇન્ડસ્ટ્રીઝના નામે રૂા.૧૫.૬૦ કરોડના બોગસ બિલીંગના વ્યવહારો દર્શાવી અન્ય વેપારીઓને રૂા.૮.૪૫ કરોડની વેરાશાખ તબદીલ કરેલ તથા અનરજીસ્ટર્ડ પર્સન પાસેથી દર્શાવેલ ખરીદીઓનાં વેચાણો પર ઉઘરાવેલ રૂા.૧.૯૭ કરોડોનો વેરો સરકારમાં જમા કરાવેલ નથી. તેમણે કુલ રૂા.૧૦.૪૨ કરોડની સરકારની વેરાકીય આવકને નુકશાન પહોંચાડેલ છે.

યુનાઇટેડ સ્ટેટ્સ બ્યુરો ઓફ લેબર સ્ટેટિસ્ટિક્સ અનુસાર, 2008 માં અપરાધ દ્રશ્ય તપાસકર્તાઓ માટેનો સરેરાશ પગાર $ 55,040 હતો, અથવા કલાક દીઠ 23.97 ડોલર હતો. તે જ વર્ષે અમેરિકામાં $ 32,000 થી 83,000 ડોલરની વચ્ચેનો પગાર.

તેમજ ત્રણ દિવસ પહેલા ઢાંઢણી ગામની પરિણીતાએ પણ તેનાં પ્રેમી સાથે ભાગી જઈ બંને પ્રેમી પંખીડાએ આપઘાત કરી લેતાં હાલ સમગ્ર શહેરમાં ભારે ચકચાર મચી ગઇ છે.

જોકે, એ જોવું રસપ્રદ રહેશે કે ટ્વિટર પોતાના આ ખાસ યુઝર્સને જતા કેવી રીતે રોકશે, અને શું અમિતાભ બચ્ચના ટ્વિટર છોડવાના સંકેત સામે ટ્વિટર કોઈ નિવેદન આપે છે કે નહીં.

### Convert into parquet

In [4]:
if not os.path.exists(output_file):
    import pandas as pd
    with open(input_file, "r", encoding="utf-8") as f:
        lines = [line.strip() for line in f if line.strip()]
    pd.DataFrame({"text": lines}).to_parquet(output_file, index=False)
    print(f"Converted {len(lines):,} lines to '{output_file}'")
else:
    print(f"Parquet already exists: {output_file}")

Parquet already exists: C:\Users\91942\OneDrive\Desktop\NLP\Lab 1\gujarati.parquet

### load sample of 1st 50,000

In [5]:
import pyarrow.parquet as pq
pf = pq.ParquetFile(output_file)
print(f"Total rows in parquet: {pf.metadata.num_rows:,}")
SAMPLE = 50_000
first_batch = next(pf.iter_batches(batch_size=SAMPLE, columns=["text"]))
import pandas as pd
df = first_batch.to_pandas()
print(f"Loaded sample of {len(df):,} rows for processing")
df.head()

Total rows in parquet: 21,798,320
Loaded sample of 50,000 rows for processing

                                                text
0  આ વીડિયો જુઓ: ઊંઝા માર્કેટયાર્ડ આજથી 25 જુલાઈ ...
1                             મિથેનોલ આવ્યો ક્યાંથી?
2  આખરે ત્રણ રાજ્યોમાં મળેલ હાર પર કોંગ્રેસ અધ્યક...
3  આ આંકડો માટે, અને વજન ઘટાડવા માટે પ્રકાશનનો દિ...
4  આ ઠેકાઓ પરથી લીમડી તેમજ ઝાલોદના બૂટલેગરો વિદેશ...

### Date and time identifier

* Gujarati Digits (0-9): Fall within the Unicode range \u0ae6 to \u0aef.

* Gujarati Letters (Months): All Gujarati characters fall within the Unicode block \u0A80 to \u0AFF.

In [13]:
gujarati_unicode_map = {
    "0": "\u0ae6",
    "1": "\u0ae7",
    "2": "\u0ae8",
    "3": "\u0ae9",
    "4": "\u0aea",
    "5": "\u0aeb",
    "6": "\u0aec",
    "7": "\u0aed",
    "8": "\u0aee",
    "9": "\u0aef"
}

In [ ]:
def extract_guj_date(text):
    num_pattern = r"[\u0ae6-\u0aef]{1,2}[\-\/\.][\u0ae6-\u0aef]{1,2}[\-\/\.][\u0ae6-\u0aef]{2,4}"
    text_pattern = r"[\u0ae6-\u0aef]{1,2}\s+[\u0a80-\u0aff]+\s+[\u0ae6-\u0aef]{2,4}"
    combine_pattern = r"{num_pattern}|{text_pattern}"
    return re.findall(num_pattern, text)


# Matches HH:MM or HH:MM:SS 
def extract_guj_time(text):
    time_pattern = r"[\u0ae6-\u0aef]{1,2}:[\u0ae6-\u0aef]{2}(?::[\u0ae6-\u0aef]{2})?"
    return re.findall(time_pattern, text)

In [ ]:
print(extract_guj_date("મારી ફ્લાઇટ ૧૫/૦૮/૨૦૨૬ ના રોજ ઉપડશે.છેલ્લું બિલ ૨૫.૧૨.૨૦૨૫ ના રોજ ચૂકવવામાં આવ્યું હતું.ગાંધીજીનો જન્મ ૦૨ ઓક્ટોબર ૧૮૬૯ માં થયો હતો."))

['૧૫/૦૮/૨૦૨૬', '૨૫.૧૨.૨૦૨૫']

In [ ]:
sample_time_text=sample_text = """
    મીટીંગ સવારે ૧૦:૩૦ કલાકે શરૂ થશે.
    ટાઈમર ૦૦:૧૫:૩૦ પર સેટ કરો.
    મારી બસ સાંજે ૫:૪૫ વાગ્યે ઉપડશે.
    """
print(extract_guj_time(sample_time_text))

['૧૦:૩૦', '૦૦:૧૫:૩૦', '૫:૪૫']

### Decimal number

In [21]:
def extract_guj_num(text):
    decimal_pattern=r"[\u0ae6-\u0aef,]+\.[\u0ae6-\u0aef]+"
    return re.findall(decimal_pattern, text)

In [22]:
sample_decimal_text = """
    આ પુસ્તકની કિંમત ૧૫૦.૫૦ રૂપિયા છે.
    મારું વજન ૬૫.૭૫ કિલોગ્રામ છે.
    તેને પરીક્ષામાં ૮૯.૯૯ ટકા મળ્યા.

    """
print(extract_guj_num(sample_decimal_text))

['૧૫૦.૫૦', '૬૫.૭૫', '૮૯.૯૯']

### Email and url extracter

* pattern is divided into four main parts: [Prefix] [Domain] . [Extension] [Optional Path]
* (?: ... ) is a "non-capturing group." It groups things together but tells Python not to extract this part separately.

In [33]:
# .%+- - for std email symbols
def extract_guj_email(text):
    email_pattern = r"[\w\u0a80-\u0aff.%+-]+@[\w\u0a80-\u0aff.-]+\.[\w\u0a80-\u0aff]{2,}"
    return re.findall(email_pattern, text)

def extract_guj_urls(text):
    url_pattern = r"(?:https?:\/\/|www\.)[\w\u0a80-\u0aff.-]+\.[\w\u0a80-\u0aff]{2,}(?:\/[\w\u0a80-\u0aff.%+-]*)*"
    return re.findall(url_pattern, text)

In [34]:
sample_email_text = """
નમસ્કાર! જો તમને કોઈ પ્રશ્ન હોય, તો તમે અમને support@example.com પર ઈમેલ કરી શકો છો. 
સ્થાનિક ભાષામાં મદદ માટે, કૃપા કરીને સીધો સંપર્ક@ગુજરાત.ભારત પર મેલ મોકલો. 

અમારી નવી યોજનાઓ વિશે જાણવા માટે https://www.google.com/search જુઓ. 
સરકારી સુવિધાઓની નોંધણી માટેની સત્તાવાર વેબસાઈટ https://ગુજરાત.સરકાર.ભારત/લોગીન છે. 
તમે www.મારો-બ્લોગ.કોમ પર પણ અમારા નવા લેખો વાંચી શકો છો.
"""
sample_urls_text = """
નમસ્કાર! જો તમને કોઈ પ્રશ્ન હોય, તો તમે અમને support@example.com પર ઈમેલ કરી શકો છો. 
સ્થાનિક ભાષામાં મદદ માટે, કૃપા કરીને સીધો સંપર્ક@ગુજરાત.ભારત પર મેલ મોકલો. 

અમારી નવી યોજનાઓ વિશે જાણવા માટે https://www.google.com/search જુઓ. 
સરકારી સુવિધાઓની નોંધણી માટેની સત્તાવાર વેબસાઈટ https://ગુજરાત.સરકાર.ભારત/લોગીન છે. 
તમે www.મારો-બ્લોગ.કોમ પર પણ અમારા નવા લેખો વાંચી શકો છો.
"""

In [35]:
print(extract_guj_email(sample_email_text))

['support@example.com', 'સંપર્ક@ગુજરાત.ભારત']

In [36]:
print(extract_guj_urls(sample_urls_text))

['https://www.google.com/search', 'https://ગુજરાત.સરકાર.ભારત/લોગીન', 'www.મારો-બ્લોગ.કોમ']

### Sentence tokenizer

In [74]:
#to view full length text
with pd.option_context('display.max_colwidth', None):
    display(df[:4])

                                                                                                                                                                                                                                                      text
0                                                                                                                                                                                                   આ વીડિયો જુઓ: ઊંઝા માર્કેટયાર્ડ આજથી 25 જુલાઈ સુધી બંધ
1                                                                                                                                                                                                                                   મિથેનોલ આવ્યો ક્યાંથી?
2  આખરે ત્રણ રાજ્યોમાં મળેલ હાર પર કોંગ્રેસ અધ્યક્ષ રાહુલ ગાંધી દ્વારા પ્રથમ પ્રતિક્રિયા આપવામાં આવી છે. તેમણે કહ્યું કે, ત્રિપુરા, નાગાલેન્ડ અને મેઘાલયમાં લોકોના જનાદેશનો સ્વાગત કરીએ છે અને આ ક્ષેત્રના લોકોનો વિશ્વાસ ફરીથી જીતીવા માટે પ્રતિબદ્ધ છીએ.
3                                                     આ આંકડો માટે, અને વજન ઘટાડવા માટે પ્રકાશનનો દિવસ વિતાવવો ઉપયોગી છે, ઉદાહરણ તરીકે, અઠવાડિયામાં એક વખત. તમારા માટે એક વિકલ્પ પસંદ કરો જે અગવડતાને કારણે નહીં કરે. સૌથી વધુ લોકપ્રિય કીફિર પર અનલોડ છે.

In [75]:
# protected_items = [] store ump@12.com or 1.2 or 1/25/2560 etc
def mask_match(match,protected_items): 
        item=match.group(0) # to get full matched text not group of it
        protected_items.append(item) # to add into protected items
        return f"__PROTECTED_{len(protected_items)-1}__"

In [76]:
def unmask_text(masked_sentences,protected_items):
    final_sentence=[]
    for sentence in masked_sentences:
        sentence = sentence.strip()
        if not sentence:
            continue

        for idx,original_item in enumerate(protected_items):
            coded_pattern = f"__PROTECTED_{idx}__"
            if coded_pattern in sentence:
                sentence = sentence.replace(coded_pattern, original_item)
        final_sentence.append(sentence)
    return final_sentence

In [78]:
def mask_text(text:str):
    if not isinstance(text, str):
            return []
    
    CHAR_BLOCK = r"\w\u0a80-\u0aff"
    GUJ_DIGIT = r"\u0ae6-\u0aef"
    
    email_pattern = rf"[{CHAR_BLOCK}.%+-]+@[{CHAR_BLOCK}.-]+\.[{CHAR_BLOCK}]{{2,}}"
    url_pattern = rf"(?:https?:\/\/|www\.)[{CHAR_BLOCK}.-]+\.[{CHAR_BLOCK}]{{2,}}(?:\/[{CHAR_BLOCK}.%+-]*)*"
    decimal_pattern = rf"[{GUJ_DIGIT}]+\.[{GUJ_DIGIT}]+"
    time_pattern = rf"[{GUJ_DIGIT}]{{1,2}}:[{GUJ_DIGIT}]{{2}}(?::[{GUJ_DIGIT}]{{2}})?"
    date_pattern = rf"[{GUJ_DIGIT}]{{2}}[./-][{GUJ_DIGIT}]{{2}}[./-][{GUJ_DIGIT}]{{2,4}}"
    
    protection_pattern = f"({url_pattern}|{email_pattern}|{date_pattern}|{time_pattern}|{decimal_pattern})"
    protected_items=[]
    masked_text = re.sub(
        protection_pattern, 
        lambda m: mask_match(m, protected_items), 
        text
    )

    return masked_text,protected_items # return full text containng __PROTECTED_{} terms

In [79]:
def normalize_ellipses(text: str) -> str:
    if not isinstance(text, str):
        return ""
        
    # Pattern explanation:
    # \.{2,}  -> Matches 2 or more consecutive ASCII dots (.., ..., .....)
    # |       -> OR
    # \u2026  -> Matches the official single-character Unicode ellipsis (…)
    pattern = r'\.{2,}|\u2026'
    
    # Replace any match with a single dot
    return re.sub(pattern, '.', text)

* ### preprocessing step

In [80]:
def normalize_text(text):
    text=normalize_ellipses(text)
    
    return text

In [81]:

#    regex-based splitter on common sentence terminators (|, ?, !, newlines).
import re

def sentence_tokenize(text: str) -> list[str]:
     
     # to mask all matched patterns
    
    # ?<= use for look prev char of current loc.
    # [...] are list of character
    # \s+ for one or more spaces
    norm_text = normalize_text(text)
    masked_text,protected_items = mask_text(norm_text)

    split_pattern = r'(?<=[.?!\u0964|])\s+|\n+'

    masked_sentences = re.split(split_pattern,masked_text) # to get mask text 
    
    unmasked_sentences = unmask_text(masked_sentences,protected_items) # to get original sentences
    
    
    return unmasked_sentences

In [82]:

sample = df['text'].iloc[5]
sents = sentence_tokenize(sample)
print(f"Sentence count in given row: {len(sents)}")
for i, s in enumerate(sents[:5], 1):
    print(f"  [{i}] {s}")

Sentence count in given row: 2
  [1] કેન્દ્રીય મંત્રી જ્યોતિરાદિત્ય સિંધિયાની જન આશિર્વાદ યાત્રા દરમિયાન ઈન્દોરના એક પોલીસ સ્ટેશનમાં પ્રાણી ક્રૂરતાનો કેસ નોંધવામાં આવ્યો છે.
  [2] ભાજપના કાર્યકરોએ જન આશીર્વાદ યાત્રા દરમિયાન.

### Word Tokenizer

In [83]:
# 8. Gujarati stopword removal
GUJARATI_STOPWORDS = {
    # common function words in Gujarati (curated list)
    "છે", "છો", "છું", "હતો", "હતી", "હતું", "હતા", "થયું", "થયા", "થઈ", "થાય",
    "અને", "કે", "તો", "જો", "જે", "તે", "આ", "એ", "આમ", "એમ", "પણ", "પર",
    "માં", "ના", "ની", "નું", "ને", "થી", "સુધી", "માટે", "સાથે", "વિના",
    "હું", "તું", "તમે", "અમે", "આપણે", "તેઓ", "આના", "તેના",
    "કરે", "કરી", "કર્યું", "કરવા", "કરવામાં", "આવે", "આવી", "આવ્યું",
    "શકે", "શકો", "જોઈએ", "હોય", "છું", "છો", "છીએ",
    "આજે", "ગઈ", "ગયા", "ગયું", "કાલે", "પછી", "પહેલા", "હવે", "ત્યારે",
    "કોઈ", "કોઈક", "કંઈક", "શું", "કેમ", "ક્યાં", "ક્યારે", "કેટલું",
    "હા", "ના", "નહીં", "ન", "બહુ", "થોડું", "બધું", "બધા", "બધી",
    "અહીં", "ત્યાં", "જ્યાં", "જ્યારે", "જોકે", "કારણ", "કેમ કે",
    "the", "a", "an", "is", "are", "was", "were", "in", "on", "at",
    "to", "of", "and", "or", "for", "with", "by", "from", "as",
}

def remove_stopwords(tokens):
    return [t for t in tokens if t not in GUJARATI_STOPWORDS]

In [84]:
# 5. Word tokenization
#    Splits on whitespace and common punctuation. Keeps Gujarati script intact.

def word_tokenize(sentence: str) -> list[str]:
    if not isinstance(sentence, str):
        return []

    mask_sentence,protected_items = mask_text(sentence)

    pattern = r"[\s,;:/\"'()\[\]{}\\<>।!?\.,\-\"“”‘’«»]+" # all punctution marks
    raw_tokens = re.split(pattern, mask_sentence) # token of protected word
    
    # Clean up any empty strings created by re.split before unmasking
    clean_tokens = [t.strip() for t in raw_tokens if t.strip()]

    unmask_words = unmask_text(clean_tokens,protected_items)

    # stopword remover
    reduce_tokens = remove_stopwords(unmask_words)
    
    print(f"Before stopword removal: {len(tokens)} tokens")
    print(f"After  stopword removal: {len(reduce_tokens)} tokens")
    print("\nFirst 20 cleaned tokens:")
    print(reduce_tokens[:20])

    return list(unmask_words)

In [85]:
tokens = word_tokenize(sample)
print(f"Word count in first row: {len(tokens)}")
print(tokens[:20])

Before stopword removal: 24 tokens
After  stopword removal: 23 tokens

First 20 cleaned tokens:
['કેન્દ્રીય', 'મંત્રી', 'જ્યોતિરાદિત્ય', 'સિંધિયાની', 'જન', 'આશિર્વાદ', 'યાત્રા', 'દરમિયાન', 'ઈન્દોરના', 'એક', 'પોલીસ', 'સ્ટેશનમાં', 'પ્રાણી', 'ક્રૂરતાનો', 'કેસ', 'નોંધવામાં', 'આવ્યો', 'ભાજપના', 'કાર્યકરોએ', 'જન']
Word count in first row: 24
['કેન્દ્રીય', 'મંત્રી', 'જ્યોતિરાદિત્ય', 'સિંધિયાની', 'જન', 'આશિર્વાદ', 'યાત્રા', 'દરમિયાન', 'ઈન્દોરના', 'એક', 'પોલીસ', 'સ્ટેશનમાં', 'પ્રાણી', 'ક્રૂરતાનો', 'કેસ', 'નોંધવામાં', 'આવ્યો', 'છે', 'ભાજપના', 'કાર્યકરોએ']

In [86]:
# 6. Lowercasing (also covers Gujarati: there is no case, but it normalises)
lower_sample = sample.lower()
print("Original :", sample[:120])
print("Lowercased:", lower_sample[:120])

Original : કેન્દ્રીય મંત્રી જ્યોતિરાદિત્ય સિંધિયાની જન આશિર્વાદ યાત્રા દરમિયાન ઈન્દોરના એક પોલીસ સ્ટેશનમાં પ્રાણી ક્રૂરતાનો કેસ નોં
Lowercased: કેન્દ્રીય મંત્રી જ્યોતિરાદિત્ય સિંધિયાની જન આશિર્વાદ યાત્રા દરમિયાન ઈન્દોરના એક પોલીસ સ્ટેશનમાં પ્રાણી ક્રૂરતાનો કેસ નોં

In [87]:
# 7. Punctuation removal
PUNCT_RE = re.compile(r"[\u0964\u0965"          # Gujarati danda, double danda
                      r"!\"#\$%&'()*+,\-./:;<=>?@\[\\\]^_`{|}~।]",
                      flags=re.UNICODE)

def remove_punctuation(text: str) -> str:
    return PUNCT_RE.sub(" ", text) if isinstance(text, str) else ""

no_punct = remove_punctuation(sample)
print("Without punctuation:")
print(no_punct[:200])

Without punctuation:
કેન્દ્રીય મંત્રી જ્યોતિરાદિત્ય સિંધિયાની જન આશિર્વાદ યાત્રા દરમિયાન ઈન્દોરના એક પોલીસ સ્ટેશનમાં પ્રાણી ક્રૂરતાનો કેસ નોંધવામાં આવ્યો છે  ભાજપના કાર્યકરોએ જન આશીર્વાદ યાત્રા દરમિયાન

In [ ]:
# 9. Full preprocessing pipeline applied to a small sample
def preprocess(text: str) -> list[str]:
    text = text.lower()
    text = remove_punctuation(text)
    toks = word_tokenize(text)
    toks = remove_stopwords(toks)
    return toks

sample_rows = df['text'].head(3).tolist()
for i, row in enumerate(sample_rows, 1):
    print(f"--- Row {i} ---")
    print("Original    :", row[:120])
    print("Preprocessed:", preprocess(row)[:15])
    print()

In [91]:
# 10. Vocabulary statistics on a small sample
from collections import Counter

sample_df = df.head(1000)            # 1k rows for speed
all_tokens = []
for t in sample_df['text']:
    all_tokens.extend(preprocess(t))

vocab = Counter(all_tokens)
print(f"Sample size       : {len(sample_df):,} rows")
print(f"Total tokens      : {len(all_tokens):,}")
print(f"Vocabulary size   : {len(vocab):,}")
print("\nTop 20 most common tokens:")
for word, freq in vocab.most_common(20):
    print(f"  {word:20s} {freq}")

Before stopword removal: 24 tokens
After  stopword removal: 8 tokens

First 20 cleaned tokens:
['વીડિયો', 'જુઓ', 'ઊંઝા', 'માર્કેટયાર્ડ', 'આજથી', '25', 'જુલાઈ', 'બંધ']
Before stopword removal: 24 tokens
After  stopword removal: 3 tokens

First 20 cleaned tokens:
['મિથેનોલ', 'આવ્યો', 'ક્યાંથી']
Before stopword removal: 24 tokens
After  stopword removal: 28 tokens

First 20 cleaned tokens:
['આખરે', 'ત્રણ', 'રાજ્યોમાં', 'મળેલ', 'હાર', 'કોંગ્રેસ', 'અધ્યક્ષ', 'રાહુલ', 'ગાંધી', 'દ્વારા', 'પ્રથમ', 'પ્રતિક્રિયા', 'આપવામાં', 'તેમણે', 'કહ્યું', 'ત્રિપુરા', 'નાગાલેન્ડ', 'મેઘાલયમાં', 'લોકોના', 'જનાદેશનો']
Before stopword removal: 24 tokens
After  stopword removal: 24 tokens

First 20 cleaned tokens:
['આંકડો', 'વજન', 'ઘટાડવા', 'પ્રકાશનનો', 'દિવસ', 'વિતાવવો', 'ઉપયોગી', 'ઉદાહરણ', 'તરીકે', 'અઠવાડિયામાં', 'એક', 'વખત', 'તમારા', 'એક', 'વિકલ્પ', 'પસંદ', 'કરો', 'અગવડતાને', 'કારણે', 'સૌથી']
Before stopword removal: 24 tokens
After  stopword removal: 55 tokens

First 20 cleaned tokens:
['ઠેકાઓ', 'પરથી', 'લીમડી', 'તેમજ', 'ઝાલોદના', 'બૂટલેગરો', 'વિદેશી', 'દારૃનો', 'મોટાપાયે', 'જથ્થો', 'ખરીદી', 'મહિસાગર', 'હાલોલ', 'ગોધરા', 'આણંદ', 'નડિયાદ', 'વડોદરા', 'શહેર', 'જિલ્લામાં', 'ઠાલવે']
Before stopword removal: 24 tokens
After  stopword removal: 23 tokens

First 20 cleaned tokens:
['કેન્દ્રીય', 'મંત્રી', 'જ્યોતિરાદિત્ય', 'સિંધિયાની', 'જન', 'આશિર્વાદ', 'યાત્રા', 'દરમિયાન', 'ઈન્દોરના', 'એક', 'પોલીસ', 'સ્ટેશનમાં', 'પ્રાણી', 'ક્રૂરતાનો', 'કેસ', 'નોંધવામાં', 'આવ્યો', 'ભાજપના', 'કાર્યકરોએ', 'જન']
Before stopword removal: 24 tokens
After  stopword removal: 35 tokens

First 20 cleaned tokens:
['ઉત્તર', 'પ્રદેશમાં', 'લગભગ', '359', 'બાળ', 'કેદીઓને', 'મુક્ત', 'આવશે', 'હાઈકોર્ટના', 'નિર્દેશોના', 'પગલે', 'કેદીઓને', 'બાળગૃહમાંથી', 'મુકત', 'આવશે', 'કેદીઓને', 'ત્રણ', 'વર્ષ', 'સુધીની', 'સજા']
Before stopword removal: 24 tokens
After  stopword removal: 31 tokens

First 20 cleaned tokens:
['યાત્રા', 'સમય', 'શુભ', 'હોવાથી', 'ટાળી', 'દેવી', 'યોગ્ય', 'રહેશે', 'અઠવાડિયે', 'ખર્ચો', 'વધારે', 'થશે', 'અઠવાડિયાના', 'અંતે', 'વાતને', 'લઈને', 'ચિંતા', 'કર્ક', 'મહિલા', 'વર્ગના']
Before stopword removal: 24 tokens
After  stopword removal: 31 tokens

First 20 cleaned tokens:
['પેટના', 'પ્રદેશમાં', 'વજન', 'આગળ', 'યોનિમાર્ગ', 'ખેંચે', 'સગર્ભા', 'સ્ત્રીઓ', 'ખૂબ', 'જ', 'મેદસ્વી', 'લોકો', 'પેટની', 'વિસ્તારમાં', 'તેમના', 'વજન', 'લઇ', 'ઘણા', 'કરતાં', 'સ્વવેન']
Before stopword removal: 24 tokens
After  stopword removal: 17 tokens

First 20 cleaned tokens:
['ખુબજ', 'મુશ્કેલ', 'હોતુ', 'આપ', 'વાતો', 'ફરી', 'વખત', 'સાંભળો', 'ક્યારેક', 'આપનાં', 'પેરેન્ટ્સે', 'આપને', 'કહી', 'ઇચ્છતી', 'સીરિઝમાં', 'સત્ય', 'દર્શાવવામાં']
Before stopword removal: 24 tokens
After  stopword removal: 12 tokens

First 20 cleaned tokens:
['48', 'જેમના', 'કાન', 'સરળતાથી', 'જોઈ', 'શકાય', 'તેવાં', 'પ્રાણીઓનાં', 'નામ', 'જણાવો', 'નમૂનારૂપ', 'ઉત્તર']
Before stopword removal: 24 tokens
After  stopword removal: 51 tokens

First 20 cleaned tokens:
['મિલનભાઇ', 'હરીશભાઇ', 'માવાણીએ', 'ચાર્મી', 'ઇન્ડસ્ટ્રીઝના', 'નામે', 'રૂા', '૧૫', '૬૦', 'કરોડના', 'બોગસ', 'બિલીંગના', 'વ્યવહારો', 'દર્શાવી', 'અન્ય', 'વેપારીઓને', 'રૂા', '૮', '૪૫', 'કરોડની']
Before stopword removal: 24 tokens
After  stopword removal: 32 tokens

First 20 cleaned tokens:
['યુનાઇટેડ', 'સ્ટેટ્સ', 'બ્યુરો', 'ઓફ', 'લેબર', 'સ્ટેટિસ્ટિક્સ', 'અનુસાર', '2008', 'અપરાધ', 'દ્રશ્ય', 'તપાસકર્તાઓ', 'માટેનો', 'સરેરાશ', 'પગાર', '55', '040', 'અથવા', 'કલાક', 'દીઠ', '23']
Before stopword removal: 24 tokens
After  stopword removal: 22 tokens

First 20 cleaned tokens:
['તેમજ', 'ત્રણ', 'દિવસ', 'ઢાંઢણી', 'ગામની', 'પરિણીતાએ', 'તેનાં', 'પ્રેમી', 'ભાગી', 'જઈ', 'બંને', 'પ્રેમી', 'પંખીડાએ', 'આપઘાત', 'લેતાં', 'હાલ', 'સમગ્ર', 'શહેરમાં', 'ભારે', 'ચકચાર']
Before stopword removal: 24 tokens
After  stopword removal: 20 tokens

First 20 cleaned tokens:
['જોવું', 'રસપ્રદ', 'રહેશે', 'ટ્વિટર', 'પોતાના', 'ખાસ', 'યુઝર્સને', 'જતા', 'કેવી', 'રીતે', 'રોકશે', 'અમિતાભ', 'બચ્ચના', 'ટ્વિટર', 'છોડવાના', 'સંકેત', 'સામે', 'ટ્વિટર', 'નિવેદન', 'આપે']
Before stopword removal: 24 tokens
After  stopword removal: 41 tokens

First 20 cleaned tokens:
['દેશના', 'ઝડપથી', 'વૃદ્ધિ', 'પામી', 'રહેલા', 'રિન્યૂએબલ', 'એનર્જી', 'ક્ષેત્રમાં', 'આગામી', 'પાંચ', 'વર્ષમાં', '૨૦૨૨', 'સુધીમાં', '૩', '૩૦', 'લાખ', 'રોજગારીની', 'નવી', 'તકો', 'સર્જાવાની']
Before stopword removal: 24 tokens
After  stopword removal: 9 tokens

First 20 cleaned tokens:
['ગાર્ગી', 'કૉલેજમાં', 'છેડતીનો', 'મામલો', 'સંસદમાં', 'ઉઠ્યો', 'વિપક્ષના', 'સરકાર', 'આરોપ']
Before stopword removal: 24 tokens
After  stopword removal: 106 tokens

First 20 cleaned tokens:
['સારા', 'જૂના', 'માણસ', 'inn', 'પાસે', 'આવ્યા', 'sidelets', 'તેને', 'રાહ', 'જોઈ', 'રહ્યું', 'તેને', 'જોવા', 'પ્રસન્ન', 'પુરું', 'પાડવામાં', 'જૂના', 'માણસ', 'ખવડાવી', 'તેમણે']
Before stopword removal: 24 tokens
After  stopword removal: 30 tokens

First 20 cleaned tokens:
['ઉખાણાઓ', 'બાળકો', 'પુખ્ત', 'વયના', 'લોકો', 'ઉપયોગી', 'મેમરી', 'સમજશક્તિ', 'અમને', 'આસપાસ', 'મન', 'વિશ્વના', 'દ્રષ્ટિ', 'વ્યાપક', 'તાલીમ', 'કંપની', 'સંબંધિત', 'સાંજે', 'ચા', 'રમુજી']
Before stopword removal: 24 tokens
After  stopword removal: 125 tokens

First 20 cleaned tokens:
['નર્મદા', 'જીલ્લાના', 'ડેડીયાપાડા', 'સાગબારા', 'વિસ્તારના', 'ગરીબ', 'આદીવાસી', 'ખેડુતોને', 'વધુ', 'સારો', 'ભાવ', 'આપીશ', 'તેમ', 'કહી', '૭', '૮', 'કરોડ', 'રૃપીયાની', 'તુવેરો', 'ખરીદી']
Before stopword removal: 24 tokens
After  stopword removal: 36 tokens

First 20 cleaned tokens:
['મિશિગનના', 'નો', 'ફોલ્ટ', 'વીમા', 'કાયદાઓએ', 'તમામ', 'લાઇસન્સવાળા', 'ડ્રાઇવરોને', 'તેની', 'રાજ્ય', 'લઘુતમ', 'મર્યાદા', 'લઇ', 'જવાની', 'જરૂર', 'કાર', 'વીમા', 'પ્રદાતાઓ', 'તમને', 'એક']
Before stopword removal: 24 tokens
After  stopword removal: 13 tokens

First 20 cleaned tokens:
['કેન્દ્રીય', 'કર્મચારીઓને', 'ડીએની', 'ઉપરાંત', 'મુસાફરી', 'ભથ્થું', 'શહેર', 'ભથ્થું', 'પ્રોવિડન્ટ', 'ફંડ', 'ગ્રેચ્યુઇટીમાં', 'વધારો', 'થવાનો']
Before stopword removal: 24 tokens
After  stopword removal: 7 tokens

First 20 cleaned tokens:
['વા', 'લેનારા', '80', 'દર્દીઓમાં', 'સિન્ડ્રોમ', 'જોવા', 'મળે']
Before stopword removal: 24 tokens
After  stopword removal: 28 tokens

First 20 cleaned tokens:
['વેરાવળ', 'હરસુખલાલ', 'નાથાલાલ', 'આશરા', 'ઉ', '૭પ', 'નિવૃત', 'જીઇબી', 'એન્જીનીયર', 'હીરેશનભાઇ', 'ચેતનભાઇ', 'પિતાશ્રીનું', 'તા', 'રર', '૩', 'રોજ', 'અવસાન', 'પામેલ', 'સદ્ગતનું', 'ટેલીફોનીક']
Before stopword removal: 24 tokens
After  stopword removal: 39 tokens

First 20 cleaned tokens:
['કિસ્સામાં', 'વ્યક્તિગત', 'ઉષ્ણતા', 'બિંદુ', 'આઇટીપી', 'કામ', 'એક', 'સ્વતંત્ર', 'યોજના', 'મુજબ', 'હીટિંગ', 'સિસ્ટમ', 'પ્લેટ', 'હીટ', 'એક્સ્ચેન્જર', 'પૂરી', 'પાડવામાં', '100', 'લોડ', 'રચાયેલ']
Before stopword removal: 24 tokens
After  stopword removal: 70 tokens

First 20 cleaned tokens:
['રાજપીપળા', 'પાલિકાના', 'છેલ્લા', '10', 'વર્ષના', 'યોજનાકીય', 'કામની', 'તટસ્થ', 'તપાસ', 'સાચી', 'હકીકત', 'જણાશે', 'ધારાસભ્ય', 'પી', 'ડી', 'વસાવા', 'તમારા', 'પક્ષના', 'પાલિકા', 'સભ્યોએ']
Before stopword removal: 24 tokens
After  stopword removal: 5 tokens

First 20 cleaned tokens:
['કાગદડી', 'નજીક', 'વેગનઆર', 'કારમાં', 'આગ']
Before stopword removal: 24 tokens
After  stopword removal: 44 tokens

First 20 cleaned tokens:
['ભરૂચથી', 'રાષ્ટ્રપતિ', 'અંકલેશ્વર', 'પહોંચ્યાં', 'હતાં', 'તેમણે', 'સરદાર', 'પટેલ', 'હોસ્પિટલ', 'એન્ડ', 'હાર્ટ', 'ઇન્સ્ટીટયૂટનું', 'લોકાર્પણ', 'પ્રણવ', 'મુખરજીએ', 'હોસ્પિટલની', 'તકતીનું', 'અનાવરણ', 'તહું', 'ત્યારબાદ']
Before stopword removal: 24 tokens
After  stopword removal: 27 tokens

First 20 cleaned tokens:
['રિજેક્શનના', 'ભયના', 'કારણે', 'તેમની', 'અંદર', 'એવી', 'લાગણી', 'ઉત્પન્ન', 'થવા', 'લાગે', 'ગમે', 'કાર્ય', 'કરશે', 'તેમાં', 'બીજા', 'લોકોથી', 'ક્યારેય', 'સારું', 'પ્રદર્શન', 'ભયના']
Before stopword removal: 24 tokens
After  stopword removal: 10 tokens

First 20 cleaned tokens:
['મોરબીના', 'નાગડાવાસ', 'નજીક', 'ગાડી', 'કન્ટેનર', 'પાછળ', 'ધુસી', 'જતા', 'એકનું', 'મોત']
Before stopword removal: 24 tokens
After  stopword removal: 21 tokens

First 20 cleaned tokens:
['ફિલ્મો', 'લગભગ', 'પૂરી', 'માત્ર', 'સુપર', 'મોડલ', 'સિવાય', 'શક્યત', 'જૂન', 'મહિનામાં', 'શરૂ', 'થશે', 'વીણાએ', 'કહ્યુ', '3ડી', 'ફિલ્મમાં', 'કામ', 'કરવાનો', 'અનુભવ', 'નવો']
Before stopword removal: 24 tokens
After  stopword removal: 3 tokens

First 20 cleaned tokens:
['સગર્ભાવસ્થામાં', 'ઠંડીથી', 'ઇન્હેલેશન']
Before stopword removal: 24 tokens
After  stopword removal: 8 tokens

First 20 cleaned tokens:
['ડીપીટી', 'કંડલા', 'પોર્ટ', 'ટ્રસ્ટ', 'જમીન', 'મુક્ત', 'કરવાની', 'માગણી']
Before stopword removal: 24 tokens
After  stopword removal: 21 tokens

First 20 cleaned tokens:
['આપણાં', 'શાસ્ત્રોમાં', 'ધનતેરસ', 'વિશે', 'ઘણીબધી', 'ચર્ચા', 'આવેલી', 'ધન', 'ખરીદવાનું', 'દાન', 'કરવાનું', 'મહત્ત્વ', 'સમજાવેલું', 'અહીંયાં', 'કઈ', 'રીતે', 'પૂજન', 'કરવું', 'વિશે', 'પ્રકાશ']
Before stopword removal: 24 tokens
After  stopword removal: 46 tokens

First 20 cleaned tokens:
['વિવિધ', 'કારણો', 'સ્થિતિઓને', 'લીધે', 'મેં', 'શિખવ્યું', 'સ્વ', 'સ્વથી', 'મુક્ત', 'સ્વનું', 'સાચે', 'જ', 'અસ્તિત્વ', 'મેં', 'શીખવ્યું', 'જાત', 'નથી', 'તેમ', 'છતા', 'તેમાં']
Before stopword removal: 24 tokens
After  stopword removal: 20 tokens

First 20 cleaned tokens:
['સ્ટડીમાં', 'મહિલાઓને', 'પૂછવામાં', 'કેવો', 'પાર્ટનર', 'ઇચ્છે', 'તેમણે', 'કહ્યું', 'ભરોસાના', 'પાત્ર', 'હોવા', 'જોઇએ', 'દરેક', 'પરિસ્થિતિમાં', 'સકારાત્મક', 'વલણ', 'અપનાવે', 'તેવા', 'હોવા', 'જોઇએ']
Before stopword removal: 24 tokens
After  stopword removal: 14 tokens

First 20 cleaned tokens:
['રેમડેસિવીર', 'ઇન્જેક્શનને', 'લઈ', 'રાજ્ય', 'સરકારનો', 'મોટો', 'નિર્ણય', 'અછત', 'સર્જાતા', 'આપ્યો', 'આટલા', 'મોટા', 'જથ્થાનો', 'ઓર્ડર']
Before stopword removal: 24 tokens
After  stopword removal: 47 tokens

First 20 cleaned tokens:
['71', 'માંથી', '39', 'સ્થાયી', 'કમિશન', 'પાત્ર', 'હોવાનું', 'જાણવા', 'મળ્યું', 'કેન્દ્રએ', 'જણાવ્યું', '71માંથી', '7', 'તબીબી', 'રીતે', 'અયોગ્ય', '25માં', 'અનુશાસનહીનતાના', 'ગંભીર', 'કેસો']
Before stopword removal: 24 tokens
After  stopword removal: 25 tokens

First 20 cleaned tokens:
['ઉલ્લેખનીય', 'લોકસભા', 'ચૂંટણીમાં', 'કોંગ્રેસના', 'કારમા', 'પરાજયની', 'જવાબદારી', 'સ્વીકારીને', 'રાહુલ', 'ગાંધીએ', 'પાર્ટીના', 'અધ્યક્ષ', 'પદ', 'પરથી', 'રાજીનામું', 'આપ્યું', 'હાલ', 'પાર્ટીનું', 'સુકાન', 'તેમની']
Before stopword removal: 24 tokens
After  stopword removal: 51 tokens

First 20 cleaned tokens:
['એટલું', 'જ', '26', 'એપ્રિલની', 'સાંજે', '5', 'વાગ્યાથી', 'ખાનગી', 'યાત્રી', 'વાહન', 'બસ', 'સિવાય', 'એકથી', 'અન્ય', 'જિલ્લામાં', 'જવા', 'પ્રતિબંધ', 'રહેશે', 'સમયે', 'ફક્ત']
Before stopword removal: 24 tokens
After  stopword removal: 34 tokens

First 20 cleaned tokens:
['પશુ', 'ઊભાં', 'ઊભાં', 'ખાય', 'તેમ', 'કરપાત્રી', 'થઈને', 'ઊભો', 'ઊભો', 'ખાવા', 'માંડે', 'કેટલાક', 'હિંસક', 'જીવો', 'જંગલમાં', 'એકલા', 'ફર્યા', 'તેમ', 'વનમાં', 'એકલો']
Before stopword removal: 24 tokens
After  stopword removal: 76 tokens

First 20 cleaned tokens:
['ઉપરાંત', 'sbs', 'અભ્યાસક્રમમાં', 'માનવ', 'મૂલ્યોનો', 'સમાવેશ', 'કર્યો', 'sbs', 'તમામ', 'ફેકલ્ટી', 'મેમ્બર્સે', 'યુનિવર્સલ', 'હ્યુમન', 'વેલ્યુ', 'યુએચવી', 'તાલીમ', 'લીધી', 'એઆઇસીટીઈ', 'દ્વારા', 'રજૂ']
Before stopword removal: 24 tokens
After  stopword removal: 9 tokens

First 20 cleaned tokens:
['અધિકારીઓને', 'ફાળવેલા', 'સરકારી', 'રહેઠાણો', '3', 'અઠવાડિયામાં', 'ખાલી', 'કરવાના', 'આદેશ']
Before stopword removal: 24 tokens
After  stopword removal: 54 tokens

First 20 cleaned tokens:
['એપ્રિલ–', '2', 'એપ્રિલ', 'ગુરુવારના', 'રોજ', 'રામ', 'નવમીનો', 'તહેવાર', '6', 'એપ્રિલને', 'સોમવારે', 'મહાવીર', 'જયંતી', 'ફરવા', 'જવાનો', 'પ્લાન', 'રહ્યા', '10થી', '13', 'એપ્રિલ']
Before stopword removal: 24 tokens
After  stopword removal: 28 tokens

First 20 cleaned tokens:
['બોટલ', 'પ્રિક', 'બદામ', 'ખોલી', 'વધારાની', 'કાર્યક્ષમતા', 'ઉત્પાદનના', 'પાછળના', 'વધારાના', 'વધારા', 'આધાર', 'રાખે', 'એક', 'કેન', 'ઓપનર', 'એક', 'લાકડું', 'ફ્લેટ', 'સ્ક્રુડ્રાઈવર', 'ડેન્ટિકલ્સ']
Before stopword removal: 24 tokens
After  stopword removal: 5 tokens

First 20 cleaned tokens:
['વોન', 'લેન્ગેબેક', 'સોફ્ટ', 'પેલેટ', 'રિપેર']
Before stopword removal: 24 tokens
After  stopword removal: 8 tokens

First 20 cleaned tokens:
['પોલીસે', 'મૃતદેહને', 'પોસ્ટમોર્ટમ', 'ખસેડી', 'આગળની', 'કાર્યવાહી', 'હાથ', 'ધરી']
Before stopword removal: 24 tokens
After  stopword removal: 34 tokens

First 20 cleaned tokens:
['સ્મોલકેપ', 'મિડકેપ', 'શેરોમાં', 'સારીએવી', 'ખરીદી', 'જોવા', 'મળી', 'બીએસઇના', 'મિડકેપ', 'ઈન્ડેક્સ', '0', '75', 'ટકા', 'વધીને', 'બંધ', 'રહ્યો', 'નિફ્ટીના', 'મિડકેપ', '100', 'ઇન્ડેક્સમાં']
Before stopword removal: 24 tokens
After  stopword removal: 64 tokens

First 20 cleaned tokens:
['એક', 'ખરીદદાર', 'મળી', 'nebulizers', 'મેશ', 'તેની', 'સુવાહ્યતા', 'નીચા', 'અવાજ', 'કારણે', 'હકારાત્મક', 'સમીક્ષાઓ', 'ઘણો', 'છોડી', 'દો', 'માતા', 'પિતા', 'જેની', 'બાળકો', 'અસ્થમા']
Before stopword removal: 24 tokens
After  stopword removal: 42 tokens

First 20 cleaned tokens:
['નવી', 'સેન્ટ્રોની', 'લંબાઇ', 'ઇને', 'પહોળાઇ', 'કરતા', 'વધારે', 'રાખવામાં', 'જેથી', 'દેખાવમાં', 'કરતા', 'દમદાર', 'લાગે', 'કારમાં', '17', '64', 'સેન્ટીમીટરની', 'ટચસ્ક્રીન', 'ઇન્ફોટેન્ટમેન્ટ', 'સીસ્ટમ']
Before stopword removal: 24 tokens
After  stopword removal: 15 tokens

First 20 cleaned tokens:
['ઉલ્લેખનીય', 'વિતેલા', 'દિવસોમાં', 'રિલાયન્સે', '1500', 'રૂપિયાની', 'સિક્યોરિટી', 'ડિબોઝિટ', 'લઈને', 'ફ્રીમાં', '4જી', 'ફોન', 'ઉપલબ્ધ', 'કરાવવાની', 'જાહેરાત']
Before stopword removal: 24 tokens
After  stopword removal: 72 tokens

First 20 cleaned tokens:
['મુંબઇ', 'તા', '૧૯', 'અફઘાનિસ્તાનની', 'પરિસ્થિતિની', 'અસર', 'ભારત', 'દેશના', 'માર્કેટ', 'જોવા', 'મળી', 'રહી', 'સામાન્ય', 'રીતે', 'અફઘાનિસ્તાનમાંથી', 'દેશમાં', 'ડ્રાયફ્રૂટની', 'આયાત', 'બદામ', 'કાજુ']
Before stopword removal: 24 tokens
After  stopword removal: 67 tokens

First 20 cleaned tokens:
['આફ્રિકાના', 'જંગલમાં', 'વસતા', 'સાવજોની', 'સરખામણીમાં', 'ગીરમાં', 'સાવજો', 'વસવાટ', 'રહ્યા', 'તેનું', 'મહત્વ', 'અનેરું', 'સાવજ', 'એકમાત્ર', 'એવું', 'પ્રાણી', 'સ્ટ્રેટેજી', 'બનાવવામાં', 'માસ્ટર', 'સાવજ']
Before stopword removal: 24 tokens
After  stopword removal: 53 tokens

First 20 cleaned tokens:
['મિત્રો', 'ભારત', 'દેશ', 'પ્રખ્યાત', 'રસોઇયા', 'સંજીવ', 'કપૂરે', 'વડા', 'પ્રધાન', 'મોદીના', 'ખાવા', 'પીવાની', 'જરુરી', 'વાતો', 'શેર', 'જેમા', 'સંજીવ', 'કપૂરે', 'સંયુક્ત', 'આરબ']
Before stopword removal: 24 tokens
After  stopword removal: 121 tokens

First 20 cleaned tokens:
['જંબુસર', 'તાલુકાના', 'વહેલમ', 'ગામની', 'સીમમા', 'આવીને', 'વડોદરાના', 'અટલાદરા', 'વિસ્તારના', 'રહીશે', 'પ્રેમિકાનું', 'સગપણ', 'નકકી', 'થતા', 'વિરહની', 'વેદના', 'સહન', 'થતા', 'સીમમાં', 'આવેલ']
Before stopword removal: 24 tokens
After  stopword removal: 67 tokens

First 20 cleaned tokens:
['અલબત્ત', 'તણાવ', 'સામે', 'લડવા', 'દોડવા', 'પહેલાં', 'તમારે', 'તેને', 'ઉશ્કેરેલા', 'કારણો', 'સમજવાની', 'જરૂર', 'કામ', 'જવા', 'અનિવાર્ય', 'ભારે', 'વર્કલોડ', 'અસાઇનમેન્ટની', 'અતિશય', 'રકમ']
Before stopword removal: 24 tokens
After  stopword removal: 19 tokens

First 20 cleaned tokens:
['ફ્લિપકાર્ટ', 'દ્વારા', 'તેમના', 'પ્લેટફોર્મ', 'બિગ', 'સેવિંગ', 'ડેઝ', 'સેલ', 'જાહેરાત', 'સેલ', '25મી', 'જુલાઈના', 'રોજ', 'શરૂ', 'થશે', '૨૯મી', 'જુલાઈ', 'ચાલશે', 'ફ્લિપ']
Before stopword removal: 24 tokens
After  stopword removal: 3 tokens

First 20 cleaned tokens:
['સંજોગોવશાત્', 'માત્ર', 'દારૂ']
Before stopword removal: 24 tokens
After  stopword removal: 29 tokens

First 20 cleaned tokens:
['સપા', 'નેતાએ', 'સાફ', 'કહ્યું', 'ગઠબંધન', 'હોત', 'સમાજવાદીની', 'સરકાર', 'બની', 'હોત', 'કોઇ', 'કહેતું', 'મેં', 'ગઠબંધનનું', 'સમર્થન', 'ખોટા', 'મેં', 'સાર્વજનિક', 'રૂપે', 'ગઠબંધનનો']
Before stopword removal: 24 tokens
After  stopword removal: 33 tokens

First 20 cleaned tokens:
['સમગ્ર', 'રાજ્યમાં', 'ગરમીએ', 'માઝા', 'મુકી', 'તેવામાં', 'માણસની', 'જેમ', 'મુંગા', 'પશુ', 'પ્રાણીઓ', 'ત્રાહીમામ', 'પોકારી', 'રહ્યા', 'એકતરફ', 'બેફામ', 'કાળજાળ', 'ગરમી', 'પરંતુ', 'ગરમી']
Before stopword removal: 24 tokens
After  stopword removal: 8 tokens

First 20 cleaned tokens:
['રુપાણી', '10', 'મિનિટ', 'ફોન', 'કોની', 'વાત', 'કરતા', 'રહ્યા']
Before stopword removal: 24 tokens
After  stopword removal: 6 tokens

First 20 cleaned tokens:
['બોડેલીથી', 'મુસાફરો', 'ભરી', 'રિક્ષા', 'ડભોઈ', 'રહી']
Before stopword removal: 24 tokens
After  stopword removal: 62 tokens

First 20 cleaned tokens:
['ચોમાસાને', 'લઈને', 'ચિંતાજનક', 'સમાચાર', 'આવ્યા', 'ગુજરાતમાં', 'આગામી', 'બે', 'અઠવાડિયા', 'વરસાદની', 'શક્યાતા', 'નહીંવત', 'જોવા', 'મળી', 'રહી', 'હવામાન', 'વિભાગે', 'આગાહી', 'આગામી', 'આઠ']
Before stopword removal: 24 tokens
After  stopword removal: 32 tokens

First 20 cleaned tokens:
['પાવર', 'લોડ', 'અતિસંવેદનશીલ', 'દર્દીઓને', 'હૃદયરોગ', 'સગર્ભા', 'સ્ત્રીઓ', 'બિનસલાહભર્યા', 'મસ્ક્યુલોસ્કેલિટલ', 'સિસ્ટમના', 'ચોક્કસ', 'રોગોમાં', 'પ્રતિબંધ', 'તેથી', 'મન', 'તમારા', 'પોતાના', 'શાંતિ', 'ભલામણ', 'કરીએ']
Before stopword removal: 24 tokens
After  stopword removal: 52 tokens

First 20 cleaned tokens:
['સવારથી', 'જ', 'કાળા', 'ડિબાંગ', 'વાદળો', 'વરસાદને', 'પગલે', 'શહેરનું', 'વાતાવરણ', 'હિલ', 'સ્ટેશન', 'જેવું', 'બની', 'જવા', 'પામ્યું', 'ભારે', 'વરસાદ', 'સુરજ', 'દેવતાના', 'દર્શન']
Before stopword removal: 24 tokens
After  stopword removal: 31 tokens

First 20 cleaned tokens:
['અગાઉ', 'રાધનપુર', 'મેનેજર', 'દ્વારા', 'ગોધરા', 'અંબેધામ', 'રાધનપુર', 'રૂટની', 'બસ', 'વાયા', 'શીરવા', 'માંડવી', 'દોડતી', 'તેમાં', 'અભ્યાસ', 'કરતા', 'વિદ્યાર્થીઓ', 'અપડાઉન', 'કરતા', 'બસને']
Before stopword removal: 24 tokens
After  stopword removal: 9 tokens

First 20 cleaned tokens:
['7', 'લોકો', 'સામે', 'માનસિક', 'ત્રાસ', 'મારકૂટ', 'અંગેની', 'ફરિયાદ', 'દાખલ']
Before stopword removal: 24 tokens
After  stopword removal: 5 tokens

First 20 cleaned tokens:
['સ્ટોપ્સ', 'નવા', 'ભરતી', 'સ્વાગત', 'કામ']
Before stopword removal: 24 tokens
After  stopword removal: 29 tokens

First 20 cleaned tokens:
['આયુષ', 'મંત્રાલયે', 'વર્ષની', 'યોગ', 'દિવસ', 'થીમ', 'યોગ', 'એટ', 'હોમ', 'યોગ', 'વિથ', 'ફેમીલી', 'નક્કી', 'સૌએ', 'ઘર', 'જેવી', 'સુરક્ષિત', 'જગ્યાએ', 'યોગ', 'આપની']
Before stopword removal: 24 tokens
After  stopword removal: 2 tokens

First 20 cleaned tokens:
['બોટ્સ', 'ઉમેરવાનું']
Before stopword removal: 24 tokens
After  stopword removal: 26 tokens

First 20 cleaned tokens:
['રાજકોટ', 'તા', '૧૩', 'રાષ્ટ્રીય', 'શાયર', 'ઝવેરચંદ', 'મેઘાણીના', 'પુત્રવધુ', 'પિનાકી', 'મેઘાણીના', 'માતૃશ્રી', 'કુસુમબેન', 'નાનકભાઈ', 'મેઘાણીએ', '૮૦', 'વર્ષની', 'વયે', '૬', 'નવેમ્બર', '૨૦૧૮ના']
Before stopword removal: 24 tokens
After  stopword removal: 36 tokens

First 20 cleaned tokens:
['નાણામંત્રી', 'નિર્માલ', 'સીતારમણના', 'શુક્રવારે', 'gst', 'કાઉન્સિલની', 'બેઠકમાં', 'અનેક', 'મહત્વના', 'નિર્ણયોનું', 'એલાન', 'કર્યુ', 'આમાં', 'કોરોના', 'વાયરસથી', 'બચાવની', 'દવાઓ', 'gstથી', 'છૂટ', 'વધારીને']
Before stopword removal: 24 tokens
After  stopword removal: 54 tokens

First 20 cleaned tokens:
['નવી', 'દિલ્હી', 'ગુજરાત', 'હિમાચલ', 'પ્રદેશની', 'વિધાનસભા', 'ચૂંટણીમાં', 'ભારતીય', 'જનતા', 'પાર્ટીએ', 'જીત', 'મેળવી', 'લીધી', 'પરંતુ', 'હિમાચલ', 'પ્રદેશમાં', 'સીએમ', 'પદના', 'ઉમેદવાર', 'પ્રેમકુમાર']
Before stopword removal: 24 tokens
After  stopword removal: 205 tokens

First 20 cleaned tokens:
['અહી', 'જણાવી', 'દઈએ', 'મહામારની', 'કપરી', 'સ્થીતીમાં', 'મદદરૂપ', 'બનવા', 'પ્રજાએ', 'પ્રતિનિધીઓને', 'ચુંટયા', 'તેવા', 'રાજકારણીઓ', 'આસા', 'રાખવી', 'નકામી', 'જ', 'બની', 'રહેશે', 'રાજકારણીઓ']
Before stopword removal: 24 tokens
After  stopword removal: 7 tokens

First 20 cleaned tokens:
['ભારતની', 'પડી', 'ત્રીજી', 'વિકેટ', 'ધવન', 'થયો', 'આઉટ']
Before stopword removal: 24 tokens
After  stopword removal: 49 tokens

First 20 cleaned tokens:
['યોગ', 'ગુરુ', 'બાબા', 'રામદેવની', 'સંસ્થા', 'પતંજલિ', 'યોગપીઠ', 'દ્વારા', 'આયોજિત', 'કાર્યક્રમમાં', 'પહોંચેલા', 'નાણાંપ્રધાન', 'અરુણ', 'જેટલી', 'હેલિકોપ્ટરમાં', 'ચઢતી', 'વખતે', 'ફસડી', 'પડ્યા', 'તેમના']
Before stopword removal: 24 tokens
After  stopword removal: 34 tokens

First 20 cleaned tokens:
['હનુમનાજીને', 'ખાતા', 'ખાતા', 'સાંજ', 'તેમનો', 'પેટ', 'નહી', 'ભરાયું', 'તેનાથી', 'સીતાજી', 'ખૂબ', 'પરેશાન', 'રામજીથી', 'તેમનો', 'પૂછ્યું', 'રામએ', 'કીધું', 'હનુમાનજીને', 'તુલસીના', 'બે']
Before stopword removal: 24 tokens
After  stopword removal: 10 tokens

First 20 cleaned tokens:
['છેલ્લા', '૨૪', 'કલાકમાં', 'કોરોનાના', '૮૩૮૦૯', 'પોઝિટિવ', 'કેસ', '૧૦૫૪ના', 'મોત', 'નિપજ્યા…']
Before stopword removal: 24 tokens
After  stopword removal: 3 tokens

First 20 cleaned tokens:
['વસુંધરા', 'રાજે', 'સિંધિયા']
Before stopword removal: 24 tokens
After  stopword removal: 7 tokens

First 20 cleaned tokens:
['બેભાન', 'હાલતમાં', 'ઢળી', 'પડ્યા', 'સારવારમાં', 'દમ', 'તોડ્યો']
Before stopword removal: 24 tokens
After  stopword removal: 56 tokens
